# Generated by Django 3.2 on 2023-02-12 11:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='حداکثر 50 کاراکتر مجاز است', max_length=50, verbose_name='نام')),
                ('decription', models.TextField(verbose_name='توضیحات')),
                ('picture', models.ImageField(upload_to='image/artist', verbose_name='عکس هنرمند')),
            ],
            options={
                'verbose_name': 'هنرمند',
                'verbose_name_plural': 'هنرمندان',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='لینک')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.category', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='CommingSoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(help_text='حداکثر 50 کاراکتر مجاز است', max_length=50, verbose_name='عنوان')),
                ('thumbnail', models.ImageField(upload_to='image/comming_soon', verbose_name='بندانگشتی')),
                ('relase_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
            ],
        ),
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='زمان اولین بازدید')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'آی\u200cپی',
                'verbose_name_plural': 'آی\u200cپی ها',
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network_name', models.CharField(choices=[('instagram.', 'Instagram'), ('youTube.', 'YouTube'), ('facebook.', 'Facebook'), ('twitter.', 'Twitter'), ('telegram.', 'Telegram')], help_text='نام شبکه اجتماعی را وارد کنید', max_length=50, verbose_name='شبکه اجتماعی')),
                ('url', models.URLField(max_length=500, verbose_name='لینک شبکه اجتماعی هنرمند را وار')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='لینک')),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='image/thumbnail', verbose_name='بندانگشتی')),
                ('cover', models.ImageField(upload_to='image/cover', verbose_name='کاور آهنگ')),
                ('best_song', models.BooleanField(default=True, help_text='اگر میخواهید این آهنگ در قسمت(بهترین هارا گوش دهید)قرار گیرد تیک را بزنید', verbose_name='آهنگ منتخب؟')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='music.category', verbose_name='دسته بندی')),
                ('hits', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.ipaddress')),
            ],
            options={
                'verbose_name': 'موزیک',
                'verbose_name_plural': 'موزیک ها',
            },
        ),
        migrations.CreateModel(
            name='TrackFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_quality', models.CharField(choices=[('128', 'دانلود ترک با کیفیت 128'), ('320', 'دانلود ترک با کیفیت 320')], max_length=3)),
                ('track_file', models.FileField(upload_to='music/track_file', verbose_name='اپلود فایل')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.track')),
            ],
            options={
                'verbose_name': 'فایل موزیک',
                'verbose_name_plural': 'فایل موزیک ها',
            },
        ),
        migrations.CreateModel(
            name='OriginalLinkTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_platform_name', models.CharField(choices=[('youTube.', 'YouTube'), ('spotify.', 'Spotify'), ('soundcloud', 'SoundCloud')], help_text='نام شبکه اجتماعی را وارد کنید', max_length=50, verbose_name='شبکه اجتماعی')),
                ('music_link', models.URLField(max_length=500, verbose_name='لینک اصلی موزیک را وارد کنید')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.track')),
            ],
            options={
                'verbose_name': 'لینک اصلی آهنگ',
                'verbose_name_plural': 'لینک اصلی آهنگ ها',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, help_text='حداکثر 50 کاراکتر مجاز است', max_length=50, null=True, verbose_name='عنوان')),
                ('picture', models.ImageField(upload_to='image/banner', verbose_name='عکس')),
                ('track', models.ForeignKey(help_text='لطفا آهنگ مورد نظر خود را برای این بنر مشخص کنید', on_delete=django.db.models.deletion.CASCADE, to='music.track', verbose_name='آهنگ')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
            },
        ),
    ]
