# Generated by Django 3.2 on 2023-03-10 10:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='منتشر شود؟')),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True, verbose_name='لینک')),
                ('name', models.CharField(help_text='حداکثر 50 کاراکتر مجاز است', max_length=50, verbose_name='نام')),
                ('decription', ckeditor.fields.RichTextField(verbose_name='توضیحات')),
                ('picture', models.ImageField(upload_to='images/artists/profile', verbose_name='عکس هنرمند')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/artists/thumbnails', verbose_name='عکس بندانگشتی')),
                ('small', models.ImageField(blank=True, null=True, upload_to='images/artists/smalls')),
            ],
            options={
                'verbose_name': 'هنرمند',
                'verbose_name_plural': 'هنرمندان',
            },
        ),
        migrations.CreateModel(
            name='ComingSoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(help_text='حداکثر 50 کاراکتر مجاز است', max_length=50, verbose_name='عنوان')),
                ('thumbnail', models.ImageField(upload_to='image/comming_soon', verbose_name='بندانگشتی')),
                ('status', models.BooleanField(default=True, verbose_name='منتشر شود؟')),
                ('relase_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': 'به زودی اضافه میشود ',
                'verbose_name_plural': 'به زودی اضافه میشوند',
            },
        ),
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='زمان اولین بازدید')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'آی\u200cپی',
                'verbose_name_plural': 'آی\u200cپی ها',
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='منتشر شود؟')),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True, verbose_name='لینک')),
                ('finglish_title', models.CharField(max_length=250, verbose_name='عنوان فینگلیشی')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('music_type', models.CharField(choices=[('remix', 'ریمیکس'), ('podcasat', 'پادکست'), ('other', 'دیگر')], default='remix', help_text='اگر نوع موزیک ریمیکس یا پادکست است یکی از این گزینه هارا انتخاب کنید در غیر این صورت گزینه دیگر را انتخاب کنید', max_length=15, verbose_name='نوع موزیک')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضحیات')),
                ('cover', models.ImageField(help_text='توجه داشته باشید ابعاد عکس باید 480 * 480 باشد', upload_to='images/covers', verbose_name='کاور آهنگ')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/thumbnails/')),
                ('small', models.ImageField(blank=True, null=True, upload_to='images/smalls/')),
                ('best_song', models.BooleanField(default=True, help_text='اگر میخواهید این اهنگ در قسمت بهترین آهنگ ها قرار گیرد تیک این قسمت را بزنید.', verbose_name='آهنگ منتخب؟')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='زمان اپدیت')),
                ('artists', models.ManyToManyField(related_name='tracks', to='music.Artist', verbose_name='هنرمندان')),
            ],
            options={
                'verbose_name': 'موزیک',
                'verbose_name_plural': 'موزیک ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TrackFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=250, verbose_name='عنوان')),
                ('track_file', models.FileField(upload_to='music/track_file', verbose_name='اپلود فایل')),
                ('listen_online', models.BooleanField(default=False, help_text='اگر میخواهید کاربرها این فایل را به صورت آنلاین گوش دهند این گزینه را انتخاب کنید.', verbose_name='انلاین گوش بده')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_files', to='music.track')),
            ],
            options={
                'verbose_name': 'فایل موزیک',
                'verbose_name_plural': 'فایل موزیک ها',
            },
        ),
        migrations.CreateModel(
            name='TrackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='منتشر شود؟')),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True, verbose_name='لینک')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='music.trackcategory', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته بندی موزیک',
                'verbose_name_plural': 'دسته بندی موزیک ها',
            },
        ),
        migrations.AddField(
            model_name='track',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='music.trackcategory', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='track',
            name='hits',
            field=models.ManyToManyField(editable=False, to='music.IpAddress'),
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network_name', models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('telegram', 'Telegram')], help_text='نام شبکه اجتماعی را وارد کنید', max_length=50, verbose_name='شبکه اجتماعی')),
                ('url', models.URLField(max_length=500, verbose_name='لینک شبکه اجتماعی را وار')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('category', models.ForeignKey(help_text='تمام آیتم های مربوط به دسته بندی انتخاب شده بر اساس تعداد بازدید ها در سایت قرار میگیرد.', on_delete=django.db.models.deletion.CASCADE, related_name='sidbars', to='music.trackcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'نوار کناری',
                'verbose_name_plural': 'نوارهای کناری',
            },
        ),
        migrations.CreateModel(
            name='OriginalLinkTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_platform_name', models.CharField(choices=[('link_youtube', 'YouTube'), ('link_spotify', 'Spotify'), ('link_soundclud', 'SoundCloud')], help_text='نام شبکه اجتماعی را وارد کنید', max_length=50, verbose_name='شبکه اجتماعی')),
                ('music_link', models.URLField(max_length=500, verbose_name='لینک اصلی موزیک را وارد کنید')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_link_tracks', to='music.track')),
            ],
            options={
                'verbose_name': 'لینک اصلی آهنگ',
                'verbose_name_plural': 'لینک اصلی آهنگ ها',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(help_text='حداکثر 50 کاراکتر مجاز است', max_length=50, verbose_name='عنوان')),
                ('status', models.BooleanField(default=True, verbose_name='منتشر شود؟')),
                ('picture', models.ImageField(help_text='توجه داشته باشید ابعاد عکس باید 280 * 1200 باشد', upload_to='image/banner', verbose_name='عکس')),
                ('track', models.ForeignKey(help_text='لطفا آهنگ مورد نظر خود را برای این بنر مشخص کنید', on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='music.track', verbose_name='آهنگ')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
            },
        ),
        migrations.CreateModel(
            name='ArtistCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='منتشر شود؟')),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True, verbose_name='لینک')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='music.artistcategory', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته بندی هنرمند',
                'verbose_name_plural': 'دسته بندی هنرمند ها',
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artists', to='music.artistcategory', verbose_name='دسته بندی'),
        ),
    ]
