# Generated by Django 3.2 on 2023-03-17 14:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='lyrics',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='متن آهنگ'),
        ),
    ]
