# Generated by Django 3.2 on 2023-03-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='cover',
            field=models.ImageField(help_text='توجه داشته باشید ابعاد عکس باید 480 * 480 باشد', upload_to='images/tracks/covers', verbose_name='کاور آهنگ'),
        ),
        migrations.AlterField(
            model_name='track',
            name='small',
            field=models.ImageField(blank=True, null=True, upload_to='images/tracks/smalls/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/tracks/thumbnails/'),
        ),
    ]
