# Generated by Django 3.2 on 2023-02-12 15:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20230212_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='picture',
            field=models.ImageField(help_text='توجه داشته باشید ابعاد عکس باید 280 * 1200 باشد', upload_to='image/banner', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='track',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='توضحیات'),
        ),
    ]
