# Generated by Django 3.2 on 2023-03-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_trackfile_online_catpion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackfile',
            name='online_catpion',
            field=models.CharField(default='آنلاین گوش بده', max_length=250, verbose_name='عنوان برای پخش آنلاین'),
        ),
    ]
