# Generated by Django 3.2 on 2023-03-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20230302_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistcategory',
            options={'verbose_name': 'دسته بندی هنرمند', 'verbose_name_plural': 'دسته بندی هنرمند ها'},
        ),
        migrations.AlterModelOptions(
            name='trackcategory',
            options={'verbose_name': 'دسته بندی موزیک', 'verbose_name_plural': 'دسته بندی موزیک ها'},
        ),
        migrations.RemoveField(
            model_name='artist',
            name='category',
        ),
        migrations.AddField(
            model_name='artist',
            name='category',
            field=models.ManyToManyField(related_name='artists', to='music.ArtistCategory', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='status',
            field=models.BooleanField(default=True, verbose_name='منتشر شود؟'),
        ),
        migrations.AlterField(
            model_name='artistcategory',
            name='status',
            field=models.BooleanField(default=True, verbose_name='منتشر شود؟'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='status',
            field=models.BooleanField(default=True, verbose_name='منتشر شود؟'),
        ),
        migrations.AlterField(
            model_name='comingsoon',
            name='status',
            field=models.BooleanField(default=True, verbose_name='منتشر شود؟'),
        ),
        migrations.RemoveField(
            model_name='track',
            name='category',
        ),
        migrations.AddField(
            model_name='track',
            name='category',
            field=models.ManyToManyField(related_name='artists', to='music.TrackCategory', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='track',
            name='status',
            field=models.BooleanField(default=True, verbose_name='منتشر شود؟'),
        ),
        migrations.AlterField(
            model_name='trackcategory',
            name='status',
            field=models.BooleanField(default=True, verbose_name='منتشر شود؟'),
        ),
    ]
