# Generated by Django 3.2 on 2023-04-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_track_best_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='best_track',
            field=models.BooleanField(default=False, help_text='اگر میخواهید این آهنگ جزو برترین موزیک ها باشد این گزینه را فعال کنید.', verbose_name='بهترین آهنگ'),
        ),
    ]
