# Generated by Django 3.2 on 2023-03-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20230302_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='category',
            field=models.ManyToManyField(related_name='tracks', to='music.TrackCategory', verbose_name='دسته بندی'),
        ),
    ]
