# Generated by Django 3.2 on 2023-03-03 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_track_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='category',
        ),
        migrations.AddField(
            model_name='artist',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artists', to='music.artistcategory', verbose_name='دسته بندی'),
        ),
        migrations.RemoveField(
            model_name='track',
            name='category',
        ),
        migrations.AddField(
            model_name='track',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='music.trackcategory', verbose_name='دسته بندی'),
        ),
    ]
