# Generated by Django 3.2 on 2023-02-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='podcast',
            field=models.BooleanField(default=False, help_text='اگر این موزیک پادکست است تیک این قسمت را بزنید.', verbose_name='پادکست'),
        ),
    ]
