# Generated by Django 3.2 on 2023-02-15 07:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_track_podcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 15, 7, 34, 48, 293386, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comingsoon',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 15, 7, 35, 1, 486531, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=False, help_text='اگر میخواهید این آهنگ منتشر شود تیک این قسمت را بزنید.', verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='comingsoon',
            name='status',
            field=models.BooleanField(default=False, help_text='اگر میخواهید این آهنگ منتشر شود تیک این قسمت را بزنید.', verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='track',
            name='best_song',
            field=models.BooleanField(default=True, help_text='اگر میخواهید این اهنگ در قسمت بهترین آهنگ ها قرار گیرد تیک این قسمت را بزنید.', verbose_name='آهنگ منتخب؟'),
        ),
        migrations.AlterField(
            model_name='track',
            name='status',
            field=models.BooleanField(default=False, help_text='اگر میخواهید این آهنگ منتشر شود تیک این قسمت را بزنید.', verbose_name='وضعیت'),
        ),
    ]
