# Generated by Django 3.2 on 2023-03-04 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20230303_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originallinktrack',
            name='music_platform_name',
            field=models.CharField(choices=[('link_youtube.', 'YouTube'), ('link_spotify.', 'Spotify'), ('link_soundclud', 'SoundCloud')], help_text='نام شبکه اجتماعی را وارد کنید', max_length=50, verbose_name='شبکه اجتماعی'),
        ),
        migrations.AlterField(
            model_name='originallinktrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_link_tracks', to='music.track'),
        ),
    ]
