# Generated by Django 3.2 on 2023-02-15 07:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20230215_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 15, 7, 41, 59, 707187, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='status',
            field=models.BooleanField(default=False, help_text='اگر میخواهید این آهنگ منتشر شود تیک این قسمت را بزنید.', verbose_name='وضعیت'),
        ),
    ]
