# Generated by Django 3.2 on 2023-02-15 16:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20230215_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 15, 16, 12, 13, 496196, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='status',
            field=models.BooleanField(default=False, help_text='اگر میخواهید این آهنگ منتشر شود تیک این قسمت را بزنید.', verbose_name='وضعیت'),
        ),
    ]
