# Generated by Django 3.2 on 2023-03-04 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20230304_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='finglish_title',
        ),
    ]
