# Generated by Django 3.2 on 2023-03-05 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_remove_artist_finglish_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='track',
            field=models.ForeignKey(help_text='لطفا آهنگ مورد نظر خود را برای این بنر مشخص کنید', on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='music.track', verbose_name='آهنگ'),
        ),
    ]
