# Generated by Django 3.2 on 2023-02-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_artist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='status',
            field=models.BooleanField(default=False, verbose_name='انتشار'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='status',
            field=models.BooleanField(default=False, verbose_name='انتشار'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=False, verbose_name='انتشار'),
        ),
        migrations.AlterField(
            model_name='comingsoon',
            name='status',
            field=models.BooleanField(default=False, verbose_name='انتشار'),
        ),
        migrations.AlterField(
            model_name='track',
            name='status',
            field=models.BooleanField(default=False, verbose_name='انتشار'),
        ),
    ]
