# Generated by Django 3.2 on 2023-02-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20230216_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='created',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='created',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created',
        ),
        migrations.RemoveField(
            model_name='comingsoon',
            name='created',
        ),
        migrations.RemoveField(
            model_name='track',
            name='created',
        ),
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=250, unique=True, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='status',
            field=models.BooleanField(default=False, verbose_name='منتشر شود؟'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='status',
            field=models.BooleanField(default=False, verbose_name='منتشر شود؟'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=250, unique=True, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=False, verbose_name='منتشر شود؟'),
        ),
        migrations.AlterField(
            model_name='comingsoon',
            name='status',
            field=models.BooleanField(default=False, verbose_name='منتشر شود؟'),
        ),
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=250, unique=True, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='track',
            name='status',
            field=models.BooleanField(default=False, verbose_name='منتشر شود؟'),
        ),
    ]
