# Generated by Django 3.2 on 2023-03-05 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_alter_banner_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('category', models.ForeignKey(help_text='تمام آیتم های مربوط به دسته بندی انتخاب شده بر اساس تعداد بازدید ها در سایت قرار میگیرد.', on_delete=django.db.models.deletion.CASCADE, related_name='sidbars', to='music.trackcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'نوار کناری',
                'verbose_name_plural': 'نوارهای کناری',
            },
        ),
    ]
