# Generated by Django 3.2 on 2023-02-17 14:01

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20230217_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 17, 14, 1, 2, 719579, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='track',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار'),
        ),
    ]
