# Generated by Django 3.2 on 2023-03-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebar',
            name='status',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
    ]
