# Generated by Django 3.2 on 2023-03-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_sidebar_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackfile',
            name='track_quality',
        ),
        migrations.AddField(
            model_name='trackfile',
            name='listen_online',
            field=models.BooleanField(default=False, help_text='اگر میخواهید کاربرها این فایل را به صورت آنلاین گوش دهند این گزینه را انتخاب کنید.', verbose_name='انلاین گوش بده'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='url',
            field=models.URLField(max_length=500, verbose_name='لینک شبکه اجتماعی را وار'),
        ),
    ]
