# Generated by Django 3.2 on 2023-02-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_auto_20230217_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='artists',
            field=models.ManyToManyField(related_name='tracks', to='music.Artist', verbose_name='هنرمندان'),
        ),
    ]
