# Generated by Django 3.2 on 2023-02-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_track_artists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='hits',
        ),
        migrations.AddField(
            model_name='track',
            name='hits',
            field=models.ManyToManyField(blank=True, to='music.IpAddress'),
        ),
    ]
