# Generated by Django 3.2 on 2023-02-26 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_auto_20230226_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackfile',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_files', to='music.track'),
        ),
        migrations.AlterField(
            model_name='trackfile',
            name='track_quality',
            field=models.CharField(choices=[('128', 'دانلود ترک با کیفیت 128'), ('320', 'دانلود ترک با کیفیت 320')], max_length=3, verbose_name='کیفیت آهنگ'),
        ),
    ]
