# Generated by Django 3.2 on 2023-03-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_alter_trackfile_track_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackfile',
            name='caption',
            field=models.CharField(default='مثال:دانلود آهنگ/پادکست با کیفیت 320', max_length=250, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='trackfile',
            name='track_quality',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='کیفیت آهنگ'),
        ),
    ]
