# Generated by Django 3.2 on 2023-03-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_auto_20230301_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackfile',
            name='track_quality',
            field=models.CharField(blank=True, choices=[('320', '320'), ('128', '128')], max_length=3, null=True, verbose_name='کیفیت آهنگ'),
        ),
    ]
