# Generated by Django 3.2 on 2023-03-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='picture',
            field=models.ImageField(help_text='توجه داشته باشید ابعاد تصویر باید 280 * 1200 باشد', upload_to='images/banner', verbose_name='عکس'),
        ),
    ]
