# Generated by Django 3.2 on 2023-03-13 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='زمان اپدیت')),
                ('status', models.BooleanField(default=True, verbose_name='منتشر شود؟')),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True, verbose_name='لینک')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='category.trackcategory', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته بندی موزیک',
                'verbose_name_plural': 'دسته بندی موزیک ها',
            },
        ),
        migrations.CreateModel(
            name='ArtistCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='زمان اپدیت')),
                ('status', models.BooleanField(default=True, verbose_name='منتشر شود؟')),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True, verbose_name='لینک')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='category.artistcategory', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته بندی هنرمند',
                'verbose_name_plural': 'دسته بندی هنرمند ها',
            },
        ),
    ]
