# Generated by Django 3.2 on 2023-03-16 15:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضحیات')),
                ('picture', models.ImageField(upload_to='images/about/profiles/', verbose_name='عکس پروفایل')),
            ],
            options={
                'verbose_name': 'درباره من',
                'verbose_name_plural': 'درباره من',
            },
        ),
        migrations.CreateModel(
            name='AboutWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images/about/logo/', verbose_name='لوگو')),
                ('name', models.CharField(max_length=100, verbose_name='نام وب سایت')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'درباره وب سایت',
                'verbose_name_plural': 'درباره وب سایت',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('content', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'ارتباط ',
                'verbose_name_plural': 'ارتباطاط',
            },
        ),
    ]
