# Generated by Django 3.2 on 2023-03-01 11:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضحیات')),
                ('picture', models.ImageField(upload_to='image/profile', verbose_name='عکس پروفایل')),
            ],
            options={
                'verbose_name': 'درباره',
                'verbose_name_plural': 'درباره',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'ارتباط ',
                'verbose_name_plural': 'ارتباط ها',
            },
        ),
    ]
