# Generated by Django 3.2 on 2023-03-16 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'ارتباط ', 'verbose_name_plural': 'ارتباطات'},
        ),
    ]
