# Generated by Django 3.2 on 2023-03-14 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutUs',
            new_name='AboutME',
        ),
    ]
