# Generated by Django 3.2 on 2023-03-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutwebsite',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='images/about/logo', verbose_name='فاویکون'),
        ),
    ]
