# Generated by Django 3.2 on 2023-03-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_rename_aboutus_aboutme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='title',
        ),
    ]
