# Generated by Django 3.2 on 2023-03-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_aboutwebsite_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutwebsite',
            name='favicon',
            field=models.ImageField(blank=True, help_text='ابعاد عکس 16 * 16', null=True, upload_to='images/about/logo', verbose_name='فاویکون'),
        ),
    ]
