# Generated by Django 3.2 on 2023-02-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20230212_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'درباره', 'verbose_name_plural': 'درباره'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'ارتباط ', 'verbose_name_plural': 'ارتباط ها'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
    ]
