# Generated by Django 3.2 on 2023-03-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20230314_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='description',
            new_name='content',
        ),
    ]
