# Generated by Django 3.2 on 2023-02-16 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20230212_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 16, 10, 41, 56, 17867, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='status',
            field=models.BooleanField(default=False, help_text='اگر میخواهید این آهنگ منتشر شود تیک این قسمت را بزنید.', verbose_name='وضعیت'),
        ),
    ]
