# Generated by Django 3.2 on 2023-03-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_aboutwebsite_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='name',
            field=models.CharField(default='DJ Movan', max_length=50, verbose_name='نام'),
        ),
    ]
