# Generated by Django 3.2 on 2023-03-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_contact_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='نام'),
        ),
    ]
