# Generated by Django 3.2 on 2023-03-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_rename_description_contact_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=models.TextField(verbose_name='توضیحات'),
        ),
    ]
