# Generated by Django 3.2 on 2023-03-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_aboutme_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='picture',
            field=models.ImageField(upload_to='images/about/profiles', verbose_name='عکس پروفایل'),
        ),
    ]
