# Generated by Django 3.2 on 2023-02-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20230216_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='created',
        ),
        migrations.RemoveField(
            model_name='about',
            name='status',
        ),
    ]
