# Generated by Django 3.2 on 2023-03-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_alter_socialnetwork_social_network_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='picture',
        ),
        migrations.AddField(
            model_name='artist',
            name='cover',
            field=models.ImageField(null=True, upload_to='images/artists/cover', verbose_name='عکس هنرمند'),
        ),
    ]
