# Generated by Django 3.2 on 2023-03-13 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='زمان اپدیت')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('username', models.CharField(blank=True, max_length=50, verbose_name='نام کاربری')),
                ('content', models.TextField(verbose_name='توضیحات')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شی مدل را انتخاب کنید')),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to={'app_label__in': ['music', 'artist'], 'model__in': ('artist', 'track')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='مدل را انتخاب کنید')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='زمان اپدیت')),
                ('username', models.CharField(default='Admin', max_length=50, verbose_name='نام کاربری')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comment.comment')),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'پاسخ ها',
            },
        ),
    ]
