# Generated by Django 3.2 on 2023-03-12 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentRelatedModel',
            new_name='ModelWithComment',
        ),
    ]
