# Generated by Django 3.2 on 2023-03-14 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'app_label__in': ['music', 'artist', 'about'], 'model__in': ('artist', 'track', 'aboutme')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='مدل را انتخاب کنید'),
        ),
    ]
