# Generated by Django 3.2 on 2023-03-12 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('comment', '0002_rename_commentrelatedmodel_modelwithcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelwithcomment',
            name='contet_type',
        ),
        migrations.AddField(
            model_name='modelwithcomment',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label__in': ['music', 'artist'], 'model__in': ('artist', 'track')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='مدل ها'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'app_label__in': ['music', 'artist'], 'model__in': ('artist', 'track')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='مدل را انتخاب کنید'),
        ),
    ]
